=== UW-UPL/uw-upl.github.io/.astro/collections/coordinators.schema.json
{
  "$ref": "#/definitions/coordinators",
  "definitions": {
    "coordinators": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "grade": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "hover_image": {
          "type": "string"
        },
        "study": {
          "type": "string"
        },
        "personalLink": {
          "type": "string"
        },
        "github": {
          "type": "string"
        },
        "linkedIn": {
          "type": "string"
        },
        "bio": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "isActive",
        "grade",
        "image"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== UW-UPL/uw-upl.github.io/src/content/coordinators/pranav-dronavalli.json
{
  "name": "Pranav Dronavalli",
  "isActive": true,
  "grade": "Junior",
  "study": "CS/Math",
  "github": "dronavallipranav",
  "personalLink": "https://www.dronavalli.dev/",
  "linkedIn": "pranavdronavalli",
  "image": "pranav-dronavalli-sad.jpg",
  "hover_image": "pranav-dronavalli-happy.jpg",
  "bio": "I like insects, not bugs"
}

=== UW-UPL/uw-upl.github.io/src/content/coordinators/michael-gira.json
{
  "name": "Michael Gira",
  "isActive": false,
  "grade": "Super Senior",
  "study": "CS & Entrepreneurship",
  "personalLink": "https://gira.dev",
  "github": "michaelgira23",
  "linkedIn": "michael-gira",
  "bio": "Ever since I was a little kid I've been deathly afraid of limes. For my birthday, my mother served me key lime pie and I vigorously threw up on my great grandpa. I have not communicated with him since.",
  "image": "michael-gira.jpg"
}

=== UW-UPL/uw-upl.github.io/src/content/coordinators/david-teather.json
{
  "name": "David Teather",
  "isActive": false,
  "grade": "Senior",
  "image": "david-teather.png",
  "study": "CS & Entrepreneurship",
  "personalLink": "https://dteather.com/",
  "github": "davidteather",
  "linkedIn": "davidteather/",
  "bio": "Interested in web scraping and content design."
}
